version: "3.9"

services:
  db:
    image: postgres:15
    container_name: logmein-db
    restart: always
    environment:
      POSTGRES_DB: logs_db
      POSTGRES_USER: logs_user
      POSTGRES_PASSWORD: logs_password
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  backend:
    build: ./LogMeIn/backend
    container_name: logmein-backend
    restart: always
    environment:
      DB_HOST: db
      DB_NAME: logs_db
      DB_USER: logs_user
      DB_PASSWORD: logs_password
      DB_PORT: 5432
    ports:
      - "5000:5000"
    depends_on:
      - db

  frontend:
    build: ./LogMeIn/frontend
    container_name: logmein-frontend
    restart: always
    ports:
      - "8080:80"
    depends_on:
      - backend

volumes:
  db_data:
