name: CI Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test-backend:
    runs-on: ubuntu-latest
    services:
      db:
        image: postgres:15
        env:
          POSTGRES_DB: logs_db
          POSTGRES_USER: logs_user
          POSTGRES_PASSWORD: logs_password
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready -U logs_user -d logs_db"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          cd LogMeIn/backend
          pip install -r requirements.txt

      - name: Run tests
        run: |
          cd LogMeIn/backend
          pytest -v tests/

      - name: Run flake8
        run: |
          cd LogMeIn/backend
          flake8 app.py
